apiVersion: tinkerbell.org/v1alpha1
kind: Template
metadata:
  name: commission-node
  namespace: tink-system
spec:
  data: |
    name: commission-data
    version: "0.1"
    global_timeout: 900
    tasks:
      - name: "node-commissioning"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
          - /dev/console:/dev/console
          - /lib/firmware:/lib/firmware:ro
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          GLOBAL_VALUE: "my global value"
        actions:
          - name: "check ntp"
            image: docker.io/irishgordo/cattledogs-ntp-validator:dev
            timeout: 200
            pid: host
          - name: "check stress"
            image: docker.io/irishgordo/irishgordo/cattledogs-stress-validation:dev
            timeout: 200
            pid: host
          - name: "check iops"
            image: docker.io/irishgordo/cattledogs-iops-validation:dev
            timeout: 200
            pid: host
          - name: "power off"
            image: ghcr.io/jacobweinstock/waitdaemon:latest
            timeout: 90
            pid: host
            command: ["poweroff"]
            environment:
              IMAGE: alpine
              WAIT_SECONDS: 5
