apiVersion: tinkerbell.org/v1alpha1
kind: Workflow
metadata:
  name: node7-commission
  namespace: tink-system
spec:
  bootOptions:
    bootMode: "netboot"
    toggleAllowNetboot: true
  templateRef: commission-node
  hardwareRef: hp-160-node-7
  hardwareMap:
    device_1: fc:15:b4:94:a9:23
